# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)


User.create(first_name: 'Harlan', last_name: 'Green', username: 'harlangt', password_digest: '123')
User.create(first_name: 'Alex', last_name: 'Taub', username: 'alext', password_digest: '123')
User.create(first_name: 'John', last_name: 'Smith', username: 'johns', password_digest: '123')


Listing.create(user_id: 2, vehicle_make: "Honda", vehicle_model: "S2000", vehicle_year: 2005, mileage: 15000, vehicle_zip_code: 97035, transmission: "Manual", vehicle_description: "This 2005 Honda S2000 shows just under 10k miles and was purchased by the seller in July 2018 from a friend. Finished in Sebring Silver Metallic over black leather, the car is powered by a 2.2-liter VTEC inline-four paired with a 6-speed manual transmission and a limited-slip differential. Service in May 2018 included an oil change as well as coolant and clutch fluid flushes and transmission and differential fluid changes. This AP2 is now offered with a clean Carfax report and a clean Oregon title in the seller’s name.")

Listing.create(user_id: 1, vehicle_make: "Porsche", vehicle_model: "911 Carrera Targa", vehicle_year: 1985, mileage: 187000, vehicle_zip_code: 28105, transmission: "Manual", vehicle_description: "This 1985 Porsche 911 Carrera Targa is finished in black over black vinyl and features a whale-tail spoiler as well as 964 bumpers and taillights. Power comes from a 3.2-liter flat-six mated to a 5-speed manual transaxle with a limited-slip differential, and additional modifications include staggered 16″ Fuchs wheels, H4 headlights, and Bilstein struts. The car was acquired by the seller in 2013, with subsequent work reportedly including a glass-out repaint, a transmission rebuild, replacement of body seals, a valve adjustment, a brake overhaul, chassis bracing, and more. This 911 is offered with a Carfax report and a clean North Carolina title in the seller’s name.")

Listing.create(user_id: 1, vehicle_make: "Dodge", vehicle_model: "Viper SRT-10", vehicle_year: 2005, mileage: 23000, vehicle_zip_code: 33101, transmission: "Manual", vehicle_description: "This 2005 Dodge Viper SRT-10 was sold new in Nova Scotia, imported to the US by its second owner in 2017, and acquired by the seller in Florida shortly thereafter. Power comes from an 8.3-liter V10 mated to a Tremec T56 6-speed manual gearbox, and the car is finished in silver over black. A Kenwood stereo has been added, and an oil change was reportedly conducted three months ago. This Viper shows 38k kilometers (~23k miles) and is offered with a new US-spec gauge cluster, customs and EPA documents, and a clean Florida title in the seller’s name.")

Listing.create(user_id: 1, vehicle_make: "Mercedes", vehicle_model: "560SL", vehicle_year: 1989, mileage: 97000, vehicle_zip_code: 27513, transmission: "Automatic", vehicle_description: "This 1989 Mercedes-Benz 560SL is finished in Black Pearl Metallic over gray leather and is powered by a 5.5-liter V8 paired with a 4-speed automatic transmission. The car was acquired 15 years ago by the seller’s uncle, and the odometer shows 97k miles. Recent service reportedly included an oil change and replacement of the spark plugs in February 2019. This R107 is offered in Florida on behalf of the seller’s uncle at no reserve with a color-matched removable hardtop, a clean Carfax report, partial service records, and a clean North Carolina title.")

Listing.create(user_id: 1, vehicle_make: "Ferrari", vehicle_model: "360 Modena", vehicle_year: 2000, mileage: 44000, vehicle_zip_code: 29401, transmission: "Manual", vehicle_description: "This 2000 Ferrari 360 Modena is finished in metallic grey over red leather and was sold new by The Collection of Coral Gables, Florida, where it was serviced until moving to Texas in 2008. The seller purchased the car four months ago and has since added about 1,000 of the 44k indicated miles. Power is from a 3.6L quad-cam V8 paired with a 6-speed sequential transmission, and modifications include a titanium exhaust and JL Audio stereo system with built-in subwoofers. This Ferrari is now offered in South Carolina with service records, a clean Carfax report, and a clean Wisconsin title in the seller’s name.")

Listing.create(user_id: 2, vehicle_make: "BMW", vehicle_model: "M3 Convertible 6-speed", vehicle_year: 2001, mileage: 98000, vehicle_zip_code: 85001, transmission: "Manual", vehicle_description: "This 2001 BMW M3 convertible is finished in Imola Red over black and powered by a 3.2-liter inline-six paired with a 6-speed manual gearbox. The car was sold new in Illionis and spent time in California before being acquired by the selling dealer in Arizona. Subsequent service included replacement of the rod bearings, clutch, rear tires, and interior trim. Now showing 98k miles, this E46 M3 convertible is offered with recent receipts, a Carfax report, and a clean Arizona title.")

Listing.create(user_id: 2, vehicle_make: "Acura", vehicle_model: "NSX 5-Speed", vehicle_year: 1994, mileage: 187, vehicle_zip_code: 32789, transmission: "Manual", vehicle_description: "This 1994 Acura NSX is finished in Brooklands Green over a black leather interior and shows just 187 miles. The original owner was a collector who reportedly possesses 40+ cars all showing less than 500 miles, which are kept stored in a climate-controlled facility. This NSX remained with the collection until 2018, at which point it was registered for the first time shortly before the selling dealer’s acquisition. The 3.0-liter VTEC V6 and 5-speed manual transaxle remain unmodified, and an oil change was performed earlier this year. This NSX is now offered in Maryland with the original window sticker, factory keys and manuals, a clean Carfax report, and a clean Florida title.")

Listing.create(user_id: 2, vehicle_make: "Range Rover", vehicle_model: "County", vehicle_year: 1993, mileage: 218000, vehicle_zip_code: 93921, transmission: "Automatic", vehicle_description: "This 1993 Range Rover County is a short-wheelbase California example that was purchased by the seller through a BaT Auction in November 2017. Power is provided by a 3.9-liter V8 paired with a 4-speed automatic transmission and 2-speed transfer case. Modifications consist of a coil spring conversion, woodgrain interior trim, and a new audio system installed by the seller. Other work under current ownership included replacement of the catalytic converters, heater core, shocks, steering damper, engine mounts, suspension bushings, and tires as well as a tune-up, refinishing of exterior accessories, and an R134a A/C conversion. This RRC is offered with owner’s books, two keys, recent records, a clean Carfax report, and a clean California title in the seller’s name.")

Listing.create(user_id: 2, vehicle_make: "Nissan", vehicle_model: "GT-R", vehicle_year: 2009, mileage: 41000, vehicle_zip_code: 21029, transmission: "Manual", vehicle_description: "This 2009 Nissan GT-R was purchased new by the seller in April 2009 through Sheehy Nissan in Maryland, and now has 41k miles. The car is finished in Gun Metallic over Gray leather, and features include clear paint protection film, upgraded brake pads and rotors, and more as detailed below. The twin-turbo 3.8L V6 sends 480 horsepower and 434 lb-ft of torque to all four wheels through a dual-clutch 6-speed transmission. This R35 GT-R is now offered with its window sticker, service records, a clean Carfax, factory manuals, and a clean Maryland title in the seller’s name.")

Listing.create(user_id: 2, vehicle_make: "Jaguar", vehicle_model: "XJ8", vehicle_year: 1998, mileage: 42000, vehicle_zip_code: 85641, transmission: "Automatic", vehicle_description: "This 1998 Jaguar XJ8 is a Vanden Plas model that was purchased new by the seller, with whom it remained in Scottsdale, Arizona until moving to Minneapolis, Minnesota in 2017. This long-wheelbase sedan is finished in Anthracite over a Cashmere leather interior and shows 42k miles. Power is from a 4.0-liter V8 mated to a 5-speed automatic transmission, and standard features include wood trim, ABS brakes, a sunroof, powered seats, and more. This VDP is offered by its original owner with a clean Carfax report, service records, a window sticker, and a clean Minnesota title in the seller’s name")

Listing.create(user_id: 3, vehicle_make: "Mercedes", vehicle_model: "SL55 AMG", vehicle_year: 2004, mileage: 38000, vehicle_zip_code: 97701, transmission: "Automatic", vehicle_description: "This 2004 Mercedes-Benz SL55 AMG is powered by a supercharged 5.4-liter V8 backed by a 5-speed automatic transmission and finished in Alabaster White over Alpaca Gray leather. Equipment includes COMAND navigation, dual-zone automatic climate control, Keyless Go, and a multi-function steering wheel. The car was sold new at Mercedes-Benz of Alexandria, Virginia before moving to Oregon and California with its first owner, and was reportedly acquired by the selling dealer from its second owner in December 2018. Subsequent service included Active Body Control repair, a new power steering pump, an oil/filter change, and a coolant flush. This SL55 shows 38k miles and is offered with partial service records, manuals, a clean Carfax report, and a clean Oregon title.")

Listing.create(user_id: 3, vehicle_make: "Jeep", vehicle_model: "Grand Wagoneer", vehicle_year: 1988, mileage: 135000, vehicle_zip_code: 94577, transmission: "Automatic", vehicle_description: "This 1988 Jeep Grand Wagoneer is finished in Pearl White with faux woodgrain body trim, and powered by a 360ci V8 paired with a 3-speed automatic transmission and Selec-Trac 4-wheel drive. The truck was acquired approximately a year ago out of longterm storage by the selling dealer, and subsequent servicing included an engine rebuild, new battery, drivetrain servicing, and more. This FSJ is now offered with a clean Carfax and a clean California title.")

Listing.create(user_id: 3, vehicle_make: "Mazda", vehicle_model: "RX-7", vehicle_year: 1993, mileage: 108000, vehicle_zip_code: 27514, transmission: "Automatic", vehicle_description: "This 1993 Mazda RX-7 is finished in Brilliant Black over red leather and was acquired by the seller 22 years ago. Power is from a sequentially-turbocharged 13B-REW rotary engine coupled with a 4-speed automatic transmission, and modifications include an A’PEXi cold air intake, a Racing Beat exhaust, an aluminum radiator, and a high-flow oil pump. The engine was reportedly rebuilt with upgraded apex seals in 2004, while more recent work included replacement of the radiator hoses last year. This FD RX-7 is offered at no reserve with limited service records, a Carfax report, and a clean North Carolina title in the seller’s name.")

Listing.create(user_id: 3, vehicle_make: "Aston Martin", vehicle_model: "V8 Vantage", vehicle_year: 2007, mileage: 9000, vehicle_zip_code: 75215, transmission: "Manual", vehicle_description: "
This 2007 Aston Martin V8 Vantage has just under 9k miles and is powered by a 4.3-liter V8 linked to a rear-mounted 6-speed manual transaxle. The car is said to have remained in Texas since being sold new by Aston Martin of Dallas, and it was recently acquired by the selling dealer. A service performed in preparation of the sale included mounting four new tires, flushing the brake fluid, replacing the rear trunk struts, and changing the engine oil. This Vantage is now offered with a stamped service booklet, two keys, factory manuals, a clean Carfax report, and a clean Texas title.")

Listing.create(user_id: 3, vehicle_make: "Lotus", vehicle_model: "Elise", vehicle_year: 2005, mileage: 8700, vehicle_zip_code: 37011, transmission: "Manual", vehicle_description: "This 2005 Lotus Elise was purchased in early 2005 by its first private owner, who kept it in South Dakota for more than 10 years until his passing. It then went to a dealer in Chicago, from whom the seller purchased it in September 2015. Total mileage stands at just under 8,800, of which more than 4k have been added by the seller. Power is from a mid-mounted Toyota-sourced 1.8-liter inline-four mated to a 6-speed manual transaxle. Finished in Arctic Silver over blue upholstery, this Elise was optioned with the Touring Package, which added leather trim, power windows, partial carpeting, and sound insulation. This Lotus is now offered with a clean Carfax report, service receipts, a factory tool kit, three keys, and a clean Tennessee title in the seller’s name.")

Image.create(listing_id: 1 , image_url: "https://cdn.bringatrailer.com/wp-content/uploads/2019/03/2005_honda_s2000_1553146292f66e7dff9f98764daIMG_1061-940x666.jpg")
Image.create(listing_id: 2, image_url: "https://cdn.bringatrailer.com/wp-content/uploads/2019/03/1985_porsche_911_carrera_targa_1553055089ad0257f49BA59612-0290-494A-BC03-20304662403B-e1553618561689-940x626.jpeg")
Image.create(listing_id: 3, image_url: "https://cdn.bringatrailer.com/wp-content/uploads/2019/03/5c9b9896786e8_dodge_viper_1553615706363d8427IMG_0678-e1553710723451-940x626.jpg")
Image.create(listing_id: 4, image_url: "https://cdn.bringatrailer.com/wp-content/uploads/2019/03/1989_mercedes-benz_560sl_15530480879f98764daIMG_1435-e1553616703936-940x627.jpg")
Image.create(listing_id: 5, image_url: "https://cdn.bringatrailer.com/wp-content/uploads/2019/02/2000_ferrari_360_modena_1553284625157718c82a3e2DSC_0305-940x625.jpg")
Image.create(listing_id: 6, image_url: "https://cdn.bringatrailer.com/wp-content/uploads/2019/03/5c981ad7d6e28_bmw_m3_1552728090208495d56IMG_2364-940x609.jpg")
Image.create(listing_id: 7, image_url: "https://cdn.bringatrailer.com/wp-content/uploads/2019/03/1994_acura_nsx_155319169548f87IMG_1287-940x612.jpeg")
Image.create(listing_id: 8, image_url: "https://cdn.bringatrailer.com/wp-content/uploads/2019/03/1993_land_rover_range_rover_1552959261f9f98764daBaT-Range-Rover-12-e1553533238393-940x627.jpg")
Image.create(listing_id: 9, image_url: "https://cdn.bringatrailer.com/wp-content/uploads/2019/03/2009_nissan_gt-r_1553539850f94108220190311_161709-940x621.jpg")
Image.create(listing_id: 10, image_url: "https://cdn.bringatrailer.com/wp-content/uploads/2019/01/1998_jaguar_xj8_1553544176ce7401f06001-e1553560231699-940x628.jpg")
Image.create(listing_id: 11, image_url: "https://cdn.bringatrailer.com/wp-content/uploads/2019/03/2004_mercedes-benz_sl55_amg_1553116897ff9f98764daSL55-2-e1553551083306-940x625.jpg")
Image.create(listing_id: 12, image_url: "https://cdn.bringatrailer.com/wp-content/uploads/2019/03/1988_jeep_grand_wagoneer_1552953975f9f98764da1988-Jeep-Grand-Wagoneer-2-940x623.jpg")
Image.create(listing_id: 13, image_url: "https://cdn.bringatrailer.com/wp-content/uploads/2019/03/1993_mazda_rx-7_1553266171aedeb82035d4f220190319_164116-940x574.jpg")
Image.create(listing_id: 14, image_url: "https://cdn.bringatrailer.com/wp-content/uploads/2019/03/5c92a505b3b64_aston_martin_v8_vantage_1552920671208495d56DSC6920-e1553361105422-940x594.jpg")
Image.create(listing_id: 15, image_url: "https://cdn.bringatrailer.com/wp-content/uploads/2019/03/2005_lotus_elise_15529560198ac44713d613660318191822-e1553030077739-940x626.jpg")
